# Generated by Django 5.0.3 on 2024-04-11 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_paymentinvoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='bank',
        ),
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.bank'),
        ),
    ]
