# Generated by Django 5.0.3 on 2024-04-11 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_approve', models.BooleanField(default=False)),
                ('consumer_approve', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_delivery', to='core.order')),
            ],
        ),
    ]
