# Generated by Django 5.0.3 on 2024-04-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedelivery',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
