# Generated by Django 5.0.3 on 2024-04-10 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_customers_alter_post_views'),
        ('user', '0004_rename_is_verified_serviceproviders_id_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='user.serviceproviders'),
        ),
        migrations.AlterField(
            model_name='post',
            name='customers',
            field=models.ManyToManyField(related_name='post_customers', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='post_views', to='user.profile'),
        ),
    ]
