# Generated by Django 5.0.3 on 2024-04-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_creator_alter_post_customers_and_more'),
        ('user', '0004_rename_is_verified_serviceproviders_id_verified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Service',
        ),
    ]
