# Generated by Django 5.0.3 on 2024-04-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_post_service'),
        ('user', '0007_serviceproviders_fayda_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='post_customers', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='user.profile'),
        ),
    ]
