# Generated by Django 5.0.3 on 2024-04-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_service_customers_alter_service_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='departur_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='service',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departur_time', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.service')),
            ],
        ),
    ]
