# Generated by Django 5.0.3 on 2024-04-11 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_service_departur_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='estimated_arrival_time',
        ),
        migrations.AddField(
            model_name='path',
            name='estimated_arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='path',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
