# Generated by Django 5.0.3 on 2024-04-11 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_city_alter_service_creator_alter_path_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='post.city'),
        ),
        migrations.AlterField(
            model_name='path',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origins', to='post.city'),
        ),
    ]
