# Generated by Django 5.0.3 on 2024-04-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_path_destination_alter_path_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customers',
        ),
    ]
