# Generated by Django 5.0.3 on 2024-04-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_service_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='departur_time',
            new_name='departure_time',
        ),
    ]
