# Generated by Django 5.0.3 on 2024-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_serviceproviders_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviders',
            old_name='is_verified',
            new_name='id_verified',
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='bank_account1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='bank_account2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='grand_father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='license_back',
            field=models.ImageField(blank=True, upload_to='user/id'),
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='license_front',
            field=models.ImageField(blank=True, upload_to='user/id'),
        ),
    ]
