# Generated by Django 5.0.3 on 2024-04-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_is_verified_serviceproviders_id_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviders',
            name='license_back',
        ),
        migrations.RemoveField(
            model_name='serviceproviders',
            name='license_front',
        ),
        migrations.RemoveField(
            model_name='serviceproviders',
            name='license_verified',
        ),
    ]
