# Generated by Django 5.0.3 on 2024-04-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_serviceproviders_license_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='id_back',
            field=models.FileField(upload_to='user/id'),
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='id_front',
            field=models.FileField(upload_to='user/id'),
        ),
    ]
