# Generated by Django 5.0.3 on 2024-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_serviceproviders_id_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviders',
            name='fayda_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='id_back',
            field=models.FileField(blank=True, upload_to='user/id'),
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='id_front',
            field=models.FileField(blank=True, upload_to='user/id'),
        ),
    ]
